### ISSUE TITLE
footprint failure with spectrum

### ISSUE THREAD

**Issue by phirstgemini** [GeminiDRSoftware/FitsStorage#23]
Hardly surprising.
```
2024-02-16 20:05:25,710 3304574:service_ingest_queue:150 INFO: Ingesting S20230512S0051_red002_dragons_ql.fits.bz2 - 4910837 (5333544 on queue)
2024-02-16 20:05:25,724 3304574:ingester:156 INFO: Adding new file table entry for S20230512S0051_red002_dragons_ql.fits.bz2
2024-02-16 20:05:26,243 3304574:provenancehistory:151 WARNING: File uses old PROVHISTORY name for HISTORY
2024-02-16 20:05:26,283 3304574:ingester:496 ERROR: Error adding Footprints Traceback (most recent call last):
  File "/opt/FitsStorage/fits_storage/core/ingester.py", line 484, in add_fitsfile
    for label, fp in footprints(diskfile.ad_object, self.l).items():
  File "/opt/FitsStorage/fits_storage/core/orm/footprint.py", line 64, in footprints
    pix_fp = [(sec.x1, sec.y1),
  File "/opt/DRAGONS/astrodata/utils.py", line 250, in __getattr__
    raise AttributeError(f"No such attribute '{attr}'")
AttributeError: No such attribute 'y1'
2024-02-16 20:05:26,294 3304574:ingester:552 INFO: Adding header id 152077 to calcachequeue

```

**Comment by phirstgemini** [comment]
This was fixed as part of the footprints / standard star bug fix.
